"""Validation and introspection utilities for detecting bugs and inconsistencies.

Integrates with:
- Quality feedback loop (adds validation issues to quality flags)
- Semantic evaluation (validates consistency)
- Response generation (validates source references match response)
- Belief extraction (validates completeness)
- Topic similarity (validates inputs)

Ground-level validation that checks actual code behavior vs intended behavior.
"""

import logging
from typing import Any, Dict, List, Optional, Tuple, Set
from dataclasses import dataclass

logger = logging.getLogger(__name__)


@dataclass
class ValidationIssue:
    """Represents a validation issue found during introspection."""
    
    severity: str  # "critical", "warning", "info"
    category: str  # "source_references", "belief_extraction", "topic_similarity", etc.
    message: str
    location: str  # Function/method name
    suggestion: Optional[str] = None
    metadata: Optional[Dict[str, Any]] = None


class ResponseValidator:
    """Validates response consistency and correctness.
    
    Ground-level validators that check actual implementation behavior.
    """
    
    @staticmethod
    def validate_source_references(
        response_text: str,
        research: Dict[str, Any],
        source_references_text: str,
    ) -> List[ValidationIssue]:
        """
        Validate that source references match the actual response text.
        
        CRITICAL: Detects bug where sources are matched to synthesis instead of response.
        
        Ground-level analysis:
        1. Response text is generated by LLM from message + context (including final_synthesis)
        2. Source references are extracted from subsolution.synthesis (NOT from response text)
        3. This creates a mismatch: sources cite synthesis claims, not response claims
        
        This validator checks if cited claims appear in the actual response text.
        """
        issues = []
        
        if not research or not isinstance(research, dict):
            return issues
        
        subsolutions = research.get("subsolutions", [])
        if not subsolutions:
            return issues
        
        # Extract meaningful sentences from response text (what user actually reads)
        response_sentences = [s.strip() for s in response_text.split('.') if len(s.strip()) > 20]
        if not response_sentences:
            return issues  # Can't validate if no sentences
        
        # Extract claims from synthesis (what sources are ACTUALLY matched to in _add_source_references)
        synthesis_claims = []
        for subsolution in subsolutions:
            if not isinstance(subsolution, dict):
                continue
            synthesis = subsolution.get("synthesis", "")
            if synthesis:
                synthesis_sentences = [s.strip() for s in synthesis.split('.') if len(s.strip()) > 20]
                synthesis_claims.extend(synthesis_sentences)
        
        if not synthesis_claims or not source_references_text:
            return issues
        
        # Check each synthesis claim that appears in source references
        # Does it also appear (semantically) in the response text?
        for claim in synthesis_claims[:10]:  # Check top 10
            # Skip if claim doesn't appear in source references
            if claim not in source_references_text and claim[:50] not in source_references_text:
                continue
            
            # Check if this claim appears in response text (semantic similarity)
            claim_words = set(claim.lower().split())
            # Remove stop words for better matching
            stop_words = {"the", "a", "an", "is", "are", "was", "were", "be", "been", "being",
                         "have", "has", "had", "do", "does", "did", "will", "would", "could",
                         "should", "may", "might", "must", "can", "this", "that", "these", "those"}
            claim_words = claim_words - stop_words
            
            if not claim_words:
                continue
            
            # Check if claim appears in any response sentence
            found_in_response = False
            max_overlap_ratio = 0.0
            
            for resp_sent in response_sentences:
                resp_words = set(resp_sent.lower().split())
                resp_words = resp_words - stop_words
                
                # Compute word overlap ratio
                if claim_words:
                    overlap = len(claim_words & resp_words)
                    overlap_ratio = overlap / len(claim_words)
                    max_overlap_ratio = max(max_overlap_ratio, overlap_ratio)
                    
                    # Consider it found if >40% overlap (more strict than 30% used in matching)
                    if overlap_ratio > 0.4:
                        found_in_response = True
                        break
            
            # If claim is cited but not found in response, this is the bug
            if not found_in_response:
                issues.append(ValidationIssue(
                    severity="critical",
                    category="source_references",
                    message=f"Source reference cites claim from synthesis that doesn't appear in response text (overlap: {max_overlap_ratio:.2f})",
                    location="_add_source_references",
                    suggestion="Match sources to actual response text, not synthesis. The current implementation matches sources to subsolution.synthesis, but response text is generated separately by LLM and may have different wording. Fix: Extract claims from response_text and match to source results using semantic similarity.",
                    metadata={
                        "synthesis_claim": claim[:100],
                        "response_sentences_count": len(response_sentences),
                        "max_overlap_ratio": max_overlap_ratio,
                        "claim_words": list(claim_words)[:10],
                    }
                ))
        
        return issues
    
    @staticmethod
    def validate_belief_extraction(
        message: str,
        extracted_beliefs: List[Dict[str, Any]],
    ) -> List[ValidationIssue]:
        """
        Validate that all beliefs in message were extracted.
        
        Detects bug where only first belief is extracted.
        
        Ground-level analysis:
        - _extract_prior_beliefs loops through belief_indicators
        - When it finds a match, it extracts the belief and breaks
        - This means only the FIRST indicator's belief is extracted
        - If message has "I think X and I believe Y", only X is extracted
        """
        issues = []
        
        if not message or not isinstance(message, str):
            return issues
        
        message_lower = message.lower()
        belief_indicators = [
            "i think", "i believe", "i know", "i'm convinced",
            "i assume", "i understand", "my understanding is",
            "from what i know", "as far as i know"
        ]
        
        # Count how many belief indicators appear in message
        found_indicators = []
        for indicator in belief_indicators:
            if indicator in message_lower:
                found_indicators.append(indicator)
        
        indicator_count = len(found_indicators)
        
        # If multiple indicators but only one (or fewer) beliefs extracted, flag it
        if indicator_count > 1 and len(extracted_beliefs) < indicator_count:
            # Check if the extracted beliefs actually correspond to different indicators
            # This is a heuristic - we can't perfectly match without re-parsing
            issues.append(ValidationIssue(
                severity="warning",
                category="belief_extraction",
                message=f"Message contains {indicator_count} belief indicators ({', '.join(found_indicators[:3])}) but only {len(extracted_beliefs)} belief(s) extracted. Likely only first belief was extracted due to 'break' statement.",
                location="_extract_prior_beliefs",
                suggestion="Remove 'break' statement on line 508 to extract all beliefs, not just the first one. Current code: 'break  # Only extract one belief per message' prevents extraction of subsequent beliefs.",
                metadata={
                    "indicator_count": indicator_count,
                    "extracted_count": len(extracted_beliefs),
                    "found_indicators": found_indicators,
                }
            ))
        
        return issues
    
    @staticmethod
    def validate_topic_similarity_inputs(
        recent_queries: List[Dict[str, Any]],
        recent_topics: List[str],
    ) -> List[ValidationIssue]:
        """
        Validate that topic similarity inputs are correct.
        
        Detects issues with empty strings, wrong data structure, etc.
        
        Ground-level analysis:
        - _track_recent_query stores: {"topic": topic, "key_terms": key_terms}
        - chat() extracts: recent_topics = [q.get("topic", "") for q in self.recent_queries[-3:]]
        - If topic is empty string, it's still included in the list
        - _compute_topic_similarity processes empty strings (wastes computation, returns 0.0)
        """
        issues = []
        
        # Check for empty strings in recent_topics
        empty_indices = [i for i, topic in enumerate(recent_topics) if not topic or not topic.strip()]
        if empty_indices:
            issues.append(ValidationIssue(
                severity="info",
                category="topic_similarity",
                message=f"{len(empty_indices)} empty topic(s) in recent_topics list at indices {empty_indices}",
                location="_compute_topic_similarity",
                suggestion="Filter out empty topics in chat() before calling _compute_topic_similarity: recent_topics = [q.get('topic', '') for q in self.recent_queries[-3:] if q.get('topic')]",
                metadata={
                    "empty_count": len(empty_indices),
                    "empty_indices": empty_indices,
                    "total_topics": len(recent_topics),
                }
            ))
        
        # Check if recent_topics structure matches recent_queries structure
        if len(recent_topics) != len(recent_queries):
            issues.append(ValidationIssue(
                severity="warning",
                category="topic_similarity",
                message=f"recent_topics length ({len(recent_topics)}) doesn't match recent_queries length ({len(recent_queries)})",
                location="chat",
                suggestion="Ensure topic extraction matches query structure. Check line 154 in agent.py: recent_topics = [q.get('topic', '') for q in self.recent_queries[-3:]]",
            ))
        
        # Check if we're using the right field (topic vs topics vs key_terms)
        # The bug: code uses "topic" (singular) but might expect "topics" (plural)
        if recent_queries:
            sample_query = recent_queries[0]
            has_topic = "topic" in sample_query
            has_topics = "topics" in sample_query
            has_key_terms = "key_terms" in sample_query
            
            if not has_topic and has_key_terms:
                issues.append(ValidationIssue(
                    severity="info",
                    category="topic_similarity",
                    message="recent_queries has 'key_terms' but code uses 'topic'. Consider using key_terms for better similarity matching.",
                    location="chat",
                    suggestion="Consider using key_terms instead of topic for similarity: recent_topics = [q.get('key_terms', []) for q in self.recent_queries[-3:]]",
                ))
        
        return issues
    
    @staticmethod
    def validate_response_tiers(
        response_tiers: Dict[str, str],
        full_response: str,
    ) -> List[ValidationIssue]:
        """
        Validate that response tiers are correctly structured.
        
        Checks: summary < detailed, no empty tiers, proper lengths.
        
        Ground-level analysis:
        - Summary is created from first sentence or first 150 chars
        - If first sentence is >150 chars, it gets truncated
        - Detailed is always full_response
        - Bug: Summary may exceed intended length if first sentence is very long
        """
        issues = []
        
        if not response_tiers:
            return issues
        
        summary = response_tiers.get("summary", "")
        detailed = response_tiers.get("detailed", "")
        structured = response_tiers.get("structured", "")
        evidence = response_tiers.get("evidence", "")
        
        # Check summary length (should be <= 150 chars per design)
        if summary and len(summary) > 150:
            issues.append(ValidationIssue(
                severity="warning",
                category="response_tiers",
                message=f"Summary tier is {len(summary)} chars, exceeds intended 150 char limit. First sentence may be very long.",
                location="_create_response_tiers",
                suggestion="In _create_response_tiers (line 603), ensure summary is always <= 150 chars. Current code: 'summary = full_response.split('.')[0]' may create long summaries if first sentence is long.",
                metadata={
                    "summary_length": len(summary),
                    "intended_max": 150,
                }
            ))
        
        # Check that summary is shorter than detailed (progressive disclosure requirement)
        if summary and detailed and len(summary) >= len(detailed):
            issues.append(ValidationIssue(
                severity="warning",
                category="response_tiers",
                message=f"Summary tier ({len(summary)} chars) is not shorter than detailed tier ({len(detailed)} chars). Progressive disclosure broken.",
                location="_create_response_tiers",
                suggestion="Ensure summary is always shorter than detailed. Check line 603-605: summary creation may need better truncation logic.",
                metadata={
                    "summary_length": len(summary),
                    "detailed_length": len(detailed),
                }
            ))
        
        # Check that structured is reasonable length (should be between summary and detailed)
        if structured and detailed:
            if len(structured) > len(detailed) * 1.5:
                issues.append(ValidationIssue(
                    severity="info",
                    category="response_tiers",
                    message=f"Structured tier ({len(structured)} chars) is much longer than detailed ({len(detailed)} chars). May indicate issue with structured tier creation.",
                    location="_create_response_tiers",
                ))
        
        # Check for empty tiers
        if not summary:
            issues.append(ValidationIssue(
                severity="info",
                category="response_tiers",
                message="Summary tier is empty. Progressive disclosure may not work.",
                location="_create_response_tiers",
            ))
        
        return issues
    
    @staticmethod
    def validate_belief_alignment(
        prior_beliefs: List[Dict[str, Any]],
        evidence_text: str,
        alignment_score: float,
    ) -> List[ValidationIssue]:
        """
        Validate belief alignment computation.
        
        Checks for potential issues with contradiction detection, averaging, etc.
        
        Ground-level analysis:
        - _compute_keyword_alignment checks for contradiction_words in evidence_text
        - Problem: "not" in "not the only factor" triggers contradiction even if aligned
        - Problem: Simple word matching doesn't understand context
        - Problem: Averaging may mask strong contradictions
        """
        issues = []
        
        if not prior_beliefs or not evidence_text:
            return issues
        
        # Check if alignment is always 0.5 (neutral) - might indicate fallback
        if alignment_score == 0.5 and len(prior_beliefs) > 0:
            issues.append(ValidationIssue(
                severity="info",
                category="belief_alignment",
                message="Belief alignment is exactly 0.5 (neutral), may indicate fallback to default or no semantic alignment available",
                location="_compute_belief_alignment",
                suggestion="Check if semantic alignment is working (LLM service available?) or if keyword fallback is being used. Line 696: _compute_semantic_alignment may be falling back to keyword matching.",
            ))
        
        # Check for potential contradiction detection issues
        evidence_lower = evidence_text.lower()
        contradiction_words = {"but", "however", "contrary", "opposite", "disagree", "contradict",
                             "conflict", "different", "wrong", "incorrect", "false", "not"}
        found_contradiction_words = [w for w in contradiction_words if w in evidence_lower]
        has_contradiction_word = len(found_contradiction_words) > 0
        
        # Check for false positives: "not" in "not the only factor" doesn't mean contradiction
        if has_contradiction_word and alignment_score > 0.7:
            # Check if it's a false positive (e.g., "not the only" is actually aligned)
            belief_texts = [b.get("text", "").lower() for b in prior_beliefs]
            belief_words = set()
            for bt in belief_texts:
                belief_words.update(bt.split())
            
            # If evidence contains belief words AND contradiction words, might be nuanced
            evidence_words = set(evidence_lower.split())
            belief_overlap = len(belief_words & evidence_words)
            
            if belief_overlap > 0:
                issues.append(ValidationIssue(
                    severity="warning",
                    category="belief_alignment",
                    message=f"Evidence contains contradiction words ({found_contradiction_words}) but alignment score is high ({alignment_score:.2f}). May be false positive - evidence contains belief words ({belief_overlap} overlap) suggesting alignment despite contradiction words.",
                    location="_compute_keyword_alignment",
                    suggestion="Review contradiction detection logic on line 747. Current check 'any(word in evidence_text for word in contradiction_words)' is too naive. 'not' in 'not the only factor' doesn't mean contradiction. Consider semantic analysis or more sophisticated contradiction detection.",
                    metadata={
                        "contradiction_words_found": found_contradiction_words,
                        "alignment_score": alignment_score,
                        "belief_overlap": belief_overlap,
                    }
                ))
        
        # Check if averaging masks strong contradictions
        # This is harder to detect without individual alignment scores
        # But we can check if score is in middle range with contradiction words
        if has_contradiction_word and 0.3 < alignment_score < 0.7:
            issues.append(ValidationIssue(
                severity="info",
                category="belief_alignment",
                message=f"Alignment score ({alignment_score:.2f}) is in middle range despite contradiction words. Averaging may be masking strong contradictions.",
                location="_compute_belief_alignment",
                suggestion="Consider returning min alignment or separate contradiction detection instead of averaging all alignments. Line 707: 'return float(sum(alignments) / len(alignments))' averages all beliefs.",
            ))
        
        return issues


class IntrospectionLogger:
    """Logs introspection data for debugging and analysis.
    
    Integrates with:
    - Quality feedback loop (adds validation issues as quality flags)
    - Semantic evaluation (includes validation in quality assessment)
    """
    
    @staticmethod
    def log_validation_issues(issues: List[ValidationIssue], context: str = "") -> None:
        """Log validation issues with appropriate severity."""
        if not issues:
            return
        
        for issue in issues:
            log_msg = f"[{issue.severity.upper()}] {issue.category}: {issue.message}"
            if issue.location:
                log_msg += f" (in {issue.location})"
            if issue.suggestion:
                log_msg += f" | Suggestion: {issue.suggestion}"
            
            if issue.severity == "critical":
                logger.error(log_msg, extra={"validation_issue": issue, "context": context})
            elif issue.severity == "warning":
                logger.warning(log_msg, extra={"validation_issue": issue, "context": context})
            else:
                logger.info(log_msg, extra={"validation_issue": issue, "context": context})
    
    @staticmethod
    def convert_to_quality_flags(issues: List[ValidationIssue]) -> List[str]:
        """
        Convert validation issues to quality flags for integration with quality feedback.
        
        Quality flags are used by SemanticEvaluator to assess response quality.
        """
        flags = []
        for issue in issues:
            if issue.severity == "critical":
                flags.append(f"validation_critical_{issue.category}")
            elif issue.severity == "warning":
                flags.append(f"validation_warning_{issue.category}")
        
        return flags
    
    @staticmethod
    def log_response_metadata(
        response: Dict[str, Any],
        validation_issues: List[ValidationIssue],
    ) -> None:
        """Add validation issues to response metadata for introspection."""
        if "metadata" not in response:
            response["metadata"] = {}
        
        if "validation_issues" not in response["metadata"]:
            response["metadata"]["validation_issues"] = []
        
        # Convert issues to dict for serialization
        response["metadata"]["validation_issues"] = [
            {
                "severity": issue.severity,
                "category": issue.category,
                "message": issue.message,
                "location": issue.location,
                "suggestion": issue.suggestion,
                "metadata": issue.metadata,
            }
            for issue in validation_issues
        ]
        
        # Add summary
        critical_count = sum(1 for i in validation_issues if i.severity == "critical")
        warning_count = sum(1 for i in validation_issues if i.severity == "warning")
        
        if critical_count > 0 or warning_count > 0:
            response["metadata"]["validation_summary"] = {
                "critical": critical_count,
                "warnings": warning_count,
                "total": len(validation_issues),
            }


def validate_response(
    response: Dict[str, Any],
    message: str,
    agent_instance: Any,  # KnowledgeAgent instance
) -> List[ValidationIssue]:
    """
    Comprehensive response validation.
    
    Runs all validators and returns list of issues found.
    
    Ground-level validation:
    - Checks actual response text vs synthesis (source reference bug)
    - Validates belief extraction completeness
    - Validates topic similarity inputs
    - Validates response tier structure
    - Validates belief alignment computation
    """
    issues = []
    validator = ResponseValidator()
    
    # Get response text BEFORE source references were added (if possible)
    # This is tricky - we need to check the actual flow
    response_text = response.get("response", "")
    research = response.get("research", {})
    
    # CRITICAL VALIDATION: Source references match response text, not synthesis
    if research and response_text:
        # Extract the actual response text (before source references)
        # Source references are appended, so we can check if they match
        if "**Sources:**" in response_text:
            # Split to get response vs sources
            parts = response_text.split("**Sources:**")
            actual_response = parts[0].strip()
            source_refs_section = "**Sources:**" + parts[1] if len(parts) > 1 else ""
        else:
            actual_response = response_text
            source_refs_section = ""
        
        # Now validate: do source references cite claims from synthesis that don't appear in response?
        if source_refs_section:
            source_ref_issues = validator.validate_source_references(
                actual_response,  # Actual response text (what user reads)
                research,
                source_refs_section,  # Source references section
            )
            issues.extend(source_ref_issues)
    
    # Validate belief extraction completeness
    if hasattr(agent_instance, 'prior_beliefs'):
        belief_issues = validator.validate_belief_extraction(
            message,
            agent_instance.prior_beliefs,
        )
        issues.extend(belief_issues)
    
    # Validate topic similarity inputs (ground-level check)
    if hasattr(agent_instance, 'recent_queries'):
        # Check what was actually passed to _compute_topic_similarity
        # The bug: recent_topics may contain empty strings
        recent_topics = [q.get("topic", "") for q in agent_instance.recent_queries[-3:]]
        topic_issues = validator.validate_topic_similarity_inputs(
            agent_instance.recent_queries[-3:],
            recent_topics,
        )
        issues.extend(topic_issues)
    
    # Validate response tiers structure
    response_tiers = response.get("response_tiers", {})
    if response_tiers:
        tier_issues = validator.validate_response_tiers(
            response_tiers,
            response.get("response", ""),
        )
        issues.extend(tier_issues)
    
    # Validate belief alignment (if research was conducted)
    if research and hasattr(agent_instance, 'prior_beliefs') and agent_instance.prior_beliefs:
        # Get actual alignment scores from topology if available
        topology = research.get("topology", {})
        if topology:
            # Try to extract actual alignment from nodes
            # This is approximate - would need direct access to topology object
            final_synthesis = research.get("final_synthesis", "")
            alignment_issues = validator.validate_belief_alignment(
                agent_instance.prior_beliefs,
                str(final_synthesis),
                0.5,  # Default, would need actual score from nodes
            )
            issues.extend(alignment_issues)
    
    return issues
